# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sold_albums', models.PositiveIntegerField(default=0)),
                ('total_streams', models.PositiveIntegerField(default=0)),
                ('about_band', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concert_time', models.DateTimeField(blank=True, null=True)),
                ('concert_description', models.TextField(blank=True)),
                ('band_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('concerts', models.ManyToManyField(to='bands.Concert')),
            ],
            options={
                'permissions': (('view_pr_page', 'Can view PR pages'),),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('concert_name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('accepted_status', models.BooleanField(default=False)),
                ('is_pending_status', models.BooleanField(default=True)),
                ('concert_description', models.TextField(blank=True)),
                ('rejected_status', models.BooleanField(default=False)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_seats', models.IntegerField()),
                ('stage_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('stage_costs', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.TextField(blank=True)),
                ('light', models.TextField(blank=True)),
                ('other_technical_needs', models.TextField(blank=True)),
                ('concert_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Concert')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Stage'),
        ),
        migrations.AddField(
            model_name='concert',
            name='genre_music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Genre'),
        ),
        migrations.AddField(
            model_name='concert',
            name='light_tech',
            field=models.ManyToManyField(related_name='light_tech', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concert',
            name='sound_tech',
            field=models.ManyToManyField(related_name='sound_tech', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concert',
            name='stage_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Stage'),
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Genre'),
        ),
        migrations.AddField(
            model_name='band',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manages', to=settings.AUTH_USER_MODEL),
        ),
    ]
