# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('concert_time', models.DateTimeField(blank=True, null=True)),
                ('concert_description', models.TextField(blank=True)),
                ('band_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('concerts', models.ManyToManyField(to='bands.Concert')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_seats', models.IntegerField()),
                ('stage_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.TextField(blank=True)),
                ('light', models.TextField(blank=True)),
                ('other_technical_needs', models.TextField(blank=True)),
                ('concert_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Concert')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='genre_music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Genre'),
        ),
        migrations.AddField(
            model_name='concert',
            name='light_tech',
            field=models.ManyToManyField(related_name='light_tech', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concert',
            name='sound_tech',
            field=models.ManyToManyField(related_name='sound_tech', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concert',
            name='stage_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Stage'),
        ),
    ]
