# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_band_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
