# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20171012_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='sold_albums',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band',
            name='total_streams',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
