# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_auto_20171021_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
