# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_concert_ticket_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('concert_name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('accepted_status', models.BooleanField(default=False)),
                ('is_pending_status', models.BooleanField(default=True)),
                ('concert_description', models.TextField(blank=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Genre')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Stage')),
            ],
        ),
    ]
