# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_concert_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='concerts',
            field=models.ManyToManyField(null=True, to='bands.Concert'),
        ),
    ]
