# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_concert_genre_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
