# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_genre_description'),
        ('bands', '0005_auto_20170928_1001'),
    ]

    operations = [
    ]
