# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_merge_20171004_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='band_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bands.Band'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='concert_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='concert_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='genre_music',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bands.Genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='stage_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bands.Stage'),
            preserve_default=False,
        ),
    ]
