# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_merge_20171002_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='band_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bands.Band'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='concert_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='concert_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='genre_music',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bands.Genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='stage_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bands.Stage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festival',
            name='concerts',
            field=models.ManyToManyField(to='bands.Concert'),
        ),
    ]
