# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_auto_20170928_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
