# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0009_remove_concert_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='concert_description',
            field=models.TextField(blank=True),
        ),
    ]
