# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bands', '0010_concert_concert_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='light_tech',
            field=models.ManyToManyField(related_name='maps', to=settings.AUTH_USER_MODEL),
        ),
    ]
