# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_auto_20171002_1210'),
        ('bands', '0012_auto_20171002_1240'),
    ]

    operations = [
    ]
